#!/bin/bash
set -e
SCRIPT=$(cat << EOF
#!/bin/bash
# This shell script wrapper for "docker run" command.
# You can easy to use szyn/docker-digdag image.
set -e
docker run -it -p 65432:65432 --name docdag \
--rm -v \`pwd\`:/src szyn/docker-digdag:latest \
java -jar /usr/local/bin/digdag \$@
EOF
)

echo "${SCRIPT}" > /usr/local/bin/docdag
chmod +x /usr/local/bin/docdag
echo 'You can now use `docdag` command.'
echo 'Run `docdag help` to get started!'
